tailwind.config = {
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'error-container': '#93000a',
                'outline-variant': '#544433',
                'on-secondary-fixed': '#221b00',
                'on-background': '#e5e2e1',
                'surface-container-high': '#2a2a2a',
                'on-error-container': '#ffdad6',
                'gold-accent': '#D4AF37',
                'surface-gray': '#1E1E1E',
                'tertiary-fixed-dim': '#77d1ff',
                'inverse-on-surface': '#313030',
                'on-tertiary-fixed': '#001e2c',
                'surface-dim': '#131313',
                'on-primary': '#482900',
                error: '#ffb4ab',
                'surface-container-highest': '#353534',
                'inverse-primary': '#885200',
                'tertiary-container': '#00c1ff',
                'surface-container-lowest': '#0e0e0e',
                'on-tertiary': '#003548',
                'secondary-fixed': '#ffe16d',
                'on-error': '#690005',
                'surface-container-low': '#1c1b1b',
                'inverse-surface': '#e5e2e1',
                surface: '#131313',
                'on-surface-variant': '#dac2ad',
                'on-secondary-fixed-variant': '#544600',
                tertiary: '#91d8ff',
                'secondary-fixed-dim': '#e9c400',
                'surface-variant': '#353534',
                'surface-container': '#201f1f',
                background: '#131313',
                'secondary-container': '#ffdb3c',
                'primary-container': '#ff9d00',
                'deep-black': '#080808',
                'tertiary-fixed': '#c2e8ff',
                'on-primary-container': '#663c00',
                'primary-fixed': '#ffdcbb',
                secondary: '#fff9ef',
                'on-secondary': '#3a3000',
                'status-green': '#00E676',
                'on-secondary-container': '#725f00',
                'surface-tint': '#FFE082',
                'primary-fixed-dim': '#FFE082',
                'vibrant-orange': '#FFCC00',
                outline: '#a28d79',
                'on-tertiary-container': '#004b66',
                'on-primary-fixed': '#2c1700',
                primary: '#ffc485',
                'surface-bright': '#393939',
                'on-primary-fixed-variant': '#673d00',
                'on-surface': '#e5e2e1',
                'on-tertiary-fixed-variant': '#004d68',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                'margin-desktop': '64px',
                'container-max': '1280px',
                base: '8px',
                gutter: '24px',
                'margin-mobile': '16px',
            },
            fontFamily: {
                'body-md': ['Inter'],
                'headline-lg-mobile': ['Hanken Grotesk'],
                'display-lg': ['Hanken Grotesk'],
                'headline-md': ['Hanken Grotesk'],
                'headline-lg': ['Hanken Grotesk'],
                'body-lg': ['Inter'],
                'label-caps': ['JetBrains Mono'],
            },
            fontSize: {
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
                'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
            },
        },
    },
};
